### ISSUE TITLE
Clicking "详情" redirected me to undefined

### ISSUE THREAD

**Issue by lss233** [LF112/lcookie#1]
## Expected Behavior
Users could be redirected to a specified url by clicking the second button.

## Current Behavior
After clicked the button, I was redirected to `/undefined`.

## Steps to Reproduce
My source code:
```html
<html>
<meta charset="utf-8">
 
<body>
    <script src="lcookie.js"></script>
    <script>
        lcookie([
            ['Cookie 同意横幅', '一旦访问网站和接受该Cookie政策，即表示阁下同意按照规定的条款使用本站提供的 Cookie。 Powered by lcookie「https://github.com/lf112/lcookie」Made by LF112「https://www.lf112.net」'],
            ['同意', '详细'],
            ['#fff', 'hsla(0,0%,96%,.6)', 'hsla(0,0%,82%,.5)', '#515151', '#515151', '#a5a5a5']
        ]);
    </script>
</body>
 
</html>
```
Where the `lcookie.js` file is a copy from `https://raw.githubusercontent.com/LF112/lcookie/master/source/lcookie.js`  

I also tried to use `lcookie();` directly, but still get the same result.

**Comment by LF112** [comment]
Hi there :)

Since the re-pull of the repository caused the Url that was previously written to the array to disappear, the new Commit has fixed the problem, please re-pull the project, thank you for submitting the issues.
